package microdb.demo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/user") // This means URL's start with /demo (after Application path)
public class MainController {
  @Autowired // This means to get the bean called userRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  private UserRepository userRepository;

  @PostMapping(value = "/add2", consumes = "application/json", produces = "application/json")
  public User addNewUser2(@RequestBody User user) {
    return userRepository.save(user);
  }

  @PostMapping(path = "/add") // Map ONLY POST Requests
  public @ResponseBody Respuesta addNewUser(@RequestParam String nombre,
      @RequestParam(required = false) String correo) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    Respuesta respuesta = new Respuesta();
    if (correo == null) {
      respuesta.setResultado("No se ha podido agregar el usuario");
      respuesta.setError("No hay correo");
      return respuesta;
    }

    User userNuevo = new User();
    userNuevo.setNombre(nombre);
    try {
      userNuevo.setCorreo(correo);
    } catch (Exception e1) {
      respuesta.setResultado("No se ha podido agregar el usuario");
      respuesta.setError(e1.getMessage());
      return respuesta;
    }
    try {
      userRepository.save(userNuevo);
      respuesta.setResultado("Usuario agregado");
    } catch (Exception e) {
      respuesta.setResultado("No se ha podido agregar el usuario");
      respuesta.setError(e.getMessage());
    }

    return respuesta;

  }

  

}